### ISSUE TITLE
AE2 problem.

### ISSUE THREAD

**Issue by sinterpad** [EnderMediaDev/The-1.7.10-Pack#981]
Hello,

since our server updated to the new version of the 1.7.10 pack, my ae2 network is acting weird, i cannot use the letter "T" most of the time in none of the terminals, only after 2-3 letters it let's me type a "T", i checked if this could be my keyboard acting up, but outside the terminals my "T" works very good. it is also bound to nothing.

The second problem is that the icons of the items disappear, it is simply the icons, the numbers or the word "craft" is still there, and even the durability if the piece has it, just not the icons.
When i close and reopen my terminals. it keeps doing the same.

Everything is chunck loaded and in the same chunk, it has sufficient power has a capacitor bank with 6.000.000 rf connected to it. 
I tried to reinstall the modpack, relog, reboot, .... disconnected my network and reconnected all my machines, terminals, crafters etc one for one to see if it was a machine bugging, but that doesn't seem to be the case.

I have made a video of the problem: https://www.youtube.com/watch?v=eaY0RnYIK1M
also don't mind the music xD

greetings sinterpad

**Comment by sinterpad** [comment]
The Keybinding problem is fixed, it was actually NEI that put T to a keybind, now i just need to find a solution for the problem with ae2, but since i heve updated to 0.8.2 i have alot more random crashes, all my drivers and java are up to date, my ram is set to 8gb,....

i just removed the pack and reinstalled it with a clean install, it did not do anything. it still the same issue.

**Comment by xJon** [comment]
We need crash reports.

**Comment by sinterpad** [comment]
I have found the problem, it seems to be happening when i reach "bees" from forestry in my ae2 system, or when i search bees in my system. here is a crash report as my game crashed, just a few minutes ago.

**Comment by sinterpad** [comment]
problem is solved, the chunks near my base are corrupted

**Comment by xJon** [comment]
So can I close the issue?

**Comment by sinterpad** [comment]
Yes,  you can.


Verzonden vanaf mijn Samsung Galaxy-smartphone.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: Jon <notifications@github.com> </div><div>Datum: 13/01/2016  16:30  (GMT+01:00) </div><div>Aan: "EnderMediaDev/The-1.7.10-Pack" <The-1.7.10-Pack@noreply.github.com> </div><div>Cc: sinterpad <jakkemondelaers@hotmail.com> </div><div>Onderwerp: Re: [The-1.7.10-Pack] AE2 problem. (#981) </div><div>
</div>
So can I close the issue?

---

**Comment by xJon** [comment]
The AE2 is still an issue with existing worlds and all info should be in #984.
